import { Bonus, Recipe, RecipeCategory } from './types';

export const USER_CREDENTIALS = {
  email: 'acesso@appglicobem.com',
  password: 'GlicoBem2024@!',
};

const BONUS_CAKES_RECIPES: Recipe[] = [
  { id: 101, nome: 'Bolo de Flocão Zero Açúcar', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '8 porções', tags: ['Bolo', 'Sem Açúcar', '35 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-flocao-zero-acucar.jpeg', video: 'https://www.youtube.com/embed/2SVhtWZjlmw', ingredientes: ['4 bananas maduras', '2 ovos', 'Canela em pó a gosto', '1 xícara (chá) de aveia em flocos finos', '1 colher (chá) de fermento químico em pó'], modo_preparo: ['Preaqueça o forno a 180 °C e unte uma forma.', 'Amasse as bananas até formar um purê.', 'Em uma tigela, bata levemente os ovos.', 'Acrescente as bananas, a canela e a aveia, misturando bem.', 'Adicione o fermento e misture delicadamente.', 'Transfira para a forma e asse por 25–30 minutos.', 'Sirva após esfriar.'], substituicoes: [] },
  { id: 102, nome: 'Bolo de Chocolate Zero Açúcar', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '10–15 porções', tags: ['Bolo', 'Sem Açúcar', '45 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-chocolate-zero-acucar.jpeg', ingredientes: ['4 ovos', '1 xícara (chá) de leite', '1 xícara (chá) de eritritol', '1 xícara (chá) de cacau em pó 100%', '2 colheres (sopa) de manteiga derretida', '2 xícaras (chá) de farinha de aveia peneirada', '1 colher (sopa) de fermento químico', 'Pedacinhos de chocolate 70% (opcional)'], modo_preparo: ['Preaqueça o forno a 180 °C e unte uma forma.', 'No liquidificador, bata ovos, leite, eritritol, cacau, manteiga e farinha até obter massa homogênea.', 'Misture o fermento com uma espátula.', 'Despeje na forma e espalhe pedaços de chocolate por cima.', 'Asse por 30–40 minutos ou até passar no teste do palito.', 'Desenforme morno e sirva.'], substituicoes: [] },
  { id: 103, nome: 'Bolo de Cenoura Sem Açúcar', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '7 fatias', tags: ['Bolo', 'Sem Açúcar', '65 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-cenoura-sem-acucar.jpg', ingredientes: ['3 ovos grandes', '2 xícaras (chá) de farinha de aveia (240 g)', '4 colheres (sopa) de adoçante natural', '2 colheres (sopa) de óleo de coco (30 ml)', '1 cenoura grande (230 g)', '1 colher (sopa) de fermento químico em pó', '80 g de chocolate 60%'], modo_preparo: ['Preaqueça o forno a 180 °C e unte forma 20x10 cm.', 'No liquidificador, bata ovos, cenoura, adoçante e óleo de coco até ficar homogêneo.', 'Misture a farinha de aveia em uma tigela e adicione a mistura batida.', 'Acrescente o fermento e mexa delicadamente.', 'Asse por 30 minutos ou até passar no teste do palito.', 'Derreta o chocolate e cubra o bolo frio.'], substituicoes: [] },
  { id: 104, nome: 'Bolo Fit de Laranja', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '12–15 porções', tags: ['Bolo', 'Fit', '50 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-fit-de-laranja.png', video: 'https://www.youtube.com/embed/ykoqyHe_PBg', ingredientes: ['2 ovos', 'Suco de 2 laranjas', '4 colheres (sopa) de leite em pó desnatado', '5 colheres (sopa) de farinha de aveia', '1 xícara (chá) de xilitol (ou açúcar mascavo)', '2 colheres (sopa) de fécula de batata (ou amido de milho)', '1 colher (sopa) de fermento químico em pó', 'Raspas de laranja'], modo_preparo: ['Bata ovos e xilitol até misturar bem.', 'Acrescente o suco de 1 e ½ laranja, leite em pó, farinha de aveia e fécula. Misture.', 'Adicione o fermento e mexa até ficar homogêneo.', 'Em forma untada e polvilhada com aveia, salpique raspas no fundo.', 'Despeje a massa, salpique mais raspas e asse a 180 °C por 20 minutos.', 'Fure o bolo e regue com o restante do suco de laranja.'], substituicoes: [] },
  { id: 105, nome: 'Bolo Brownie Low Carb', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '7 porções', tags: ['Bolo', 'Low Carb', '30 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-brownie-low-carb.jpeg', ingredientes: ['160 ml de leite', '130 g de manteiga', '90 g de xilitol', '1 xícara (chá) de cacau 100%', '4 ovos', '2 xícaras (chá) de farinha de amêndoas', '2 colheres (chá) de fermento químico em pó', 'Gotas de chocolate 70% a gosto'], modo_preparo: ['Preaqueça o forno a 200 °C e forre uma forma com papel manteiga.', 'Aqueça leite e manteiga até derreter.', 'Misture xilitol e cacau até dissolver.', 'Acrescente ovos e farinha, mexendo até formar massa homogênea.', 'Incorpore o fermento.', 'Despeje na forma, espalhe gotas de chocolate e asse por 15 minutos.'], substituicoes: [] },
  { id: 106, nome: 'Bolo de Chocolate Sem Açúcar e Sem Farinha', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '1 bolo pequeno', tags: ['Bolo', 'Sem Açúcar', 'Sem Farinha', '45 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-chocolate-sem-acucar-e-sem-farinha-capa.png', video: 'https://www.youtube.com/embed/MkUujgvWblE', ingredientes: ['3 ovos', '100 ml de óleo', '3 bananas maduras', '2 xícaras de aveia em flocos', '2 colheres (sopa) de cacau em pó', '1 colher (sopa) de fermento'], modo_preparo: ['Preaqueça o forno a 200 °C e unte uma forma.', 'No liquidificador, bata ovos e óleo por 3 minutos.', 'Adicione bananas, aveia e cacau, batendo até homogeneizar.', 'Misture o fermento.', 'Asse por cerca de 30 minutos.'], substituicoes: [] },
  { id: 107, nome: 'Bolo de Aveia Sem Açúcar', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '6 porções', tags: ['Bolo', 'Sem Açúcar', '45 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-aveia-sem-acucar.jpg', ingredientes: ['2 maçãs', '130 ml de água', '1 banana', '160 g de aveia em flocos', '2 ovos', '1/2 xícara (chá) de uvas-passas', '1 colher (chá) de canela em pó', '1 colher (chá) de fermento químico em pó'], modo_preparo: ['Preaqueça o forno a 180 °C e unte forma redonda com furo (18x7 cm) com manteiga e farinha de aveia.', 'Bata as maçãs picadas com a água no liquidificador até formar creme.', 'Amasse a banana e reserve.', 'Misture aveia, creme de maçã, banana amassada e ovos até incorporar.', 'Adicione uvas-passas, canela e fermento, mexendo delicadamente.', 'Despeje na forma e asse por 35 minutos ou até passar no teste do palito.', 'Desenforme e sirva.'], substituicoes: [] },
  { id: 108, nome: 'Bolo de Fubá Diet Fácil', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '8 porções', tags: ['Bolo', 'Diet', 'Fácil', '25 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-fuba-diet-facil.jpeg', video: 'https://www.youtube.com/embed/ZeosxTVteN0', ingredientes: ['300 ml de leite de coco', '3 ovos', '3 colheres (sopa) de óleo de coco', '1 xícara (chá) de coco ralado', '1 xícara (chá) de adoçante culinário', '1 xícara (chá) de fubá', '1 colher (sopa) de canela', '1 colher (sopa) de fermento químico em pó', '2 colheres (sopa) de chia'], modo_preparo: ['Preaqueça o forno a 180 °C e unte forma.', 'Bata no liquidificador leite de coco, ovos, óleo, coco ralado, adoçante, fubá e canela até obter massa homogênea.', 'Acrescente fermento e chia, batendo por mais 1 minuto.', 'Transfira para a forma e asse por cerca de 30 minutos ou até passar no teste do palito.', 'Desenforme morno e sirva.'], substituicoes: [] },
  { id: 109, nome: 'Bolo de Limão Siciliano Fit', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '10 porções', tags: ['Bolo', 'Fit', '45 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-limao-siciliano-fit-01-730x914.jpg', ingredientes: ['1/2 xícara (chá) de xilitol', '4 colheres (sopa) de manteiga ghee sem sal', 'Extrato de baunilha a gosto', '3 ovos', '100 g de cream cheese', '1 xícara (chá) de farinha de castanhas', '1 colher (sopa) de psyllium', '1 pitada de sal', '1 limão (suco e raspas)', '1 colher (sopa) de fermento químico em pó', '1 ovo (cobertura)', '1 gema (cobertura)', '1/4 xícara (chá) de suco de limão (cobertura)', '1/4 xícara (chá) de xilitol (cobertura)', '1/4 xícara (chá) de manteiga ghee (cobertura)'], modo_preparo: ['Bata no liquidificador xilitol, manteiga, baunilha, ovos e cream cheese.', 'Em tigela, misture farinha de castanhas, psyllium, sal, suco e raspas de limão.', 'Una a mistura do liquidificador e mexa até ficar homogêneo.', 'Acrescente fermento e misture delicadamente.', 'Despeje em forma untada e asse a 180 °C por 45 minutos.', 'Para a cobertura, misture todos os ingredientes da cobertura e cozinhe em fogo baixo até engrossar.', 'Espere esfriar, cubra o bolo e sirva.'], substituicoes: [] },
  { id: 110, nome: 'Bolo Gelado de Abacaxi Sem Farinha e Sem Açúcar', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '5 porções', tags: ['Bolo', 'Sem Farinha', 'Sem Açúcar', 'Gelado'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-gelado-de-abacaxi-sem-farinha-e-sem-acucar.jpeg', ingredientes: ['1/2 abacaxi picado e fervido', '3 ovos', '1 pote (170 g) de iogurte natural', '3 colheres (sopa) de leite em pó', '3 colheres (sopa) de xilitol', '50 g de coco ralado seco', '1 colher (chá) de fermento químico em pó', '1/2 abacaxi picado e fervido (cobertura)', '1 lata de creme de leite (cobertura)', '2 colheres (sopa) de xilitol (cobertura)'], modo_preparo: ['Ferva o abacaxi da massa por 3–5 minutos e reserve.', 'Bata ovos, iogurte, leite em pó e xilitol.', 'Misture coco, abacaxi e fermento.', 'Asse em forma untada a 180 °C até dourar.', 'Para a cobertura, misture abacaxi fervido, creme de leite e xilitol até formar creme.', 'Espalhe sobre o bolo e leve à geladeira por 2 horas antes de servir.'], substituicoes: [] },
  { id: 111, nome: 'Bolo de Cacau com Gotas de Chocolate', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '10 porções', tags: ['Bolo', 'Cacau', '45 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-cacau-com-gotas-de-chocolate-01-730x913.jpg', ingredientes: ['4 ovos', '1/2 xícara (chá) de adoçante culinário', '1 colher (sopa) de extrato de baunilha', '150 ml de creme de leite fresco', '1/2 xícara (chá) de cacau em pó', '1/2 xícara (chá) de farinha de nozes', '2 colheres (sopa) de psyllium', '1 pitada de sal', '1 colher (sopa) de fermento químico em pó', 'Gotas de chocolate a gosto'], modo_preparo: ['Bata ovos, adoçante, baunilha, creme de leite até homogeneizar.', 'Adicione cacau, farinha, sal e psyllium, misturando bem.', 'Acrescente fermento e mexa delicadamente.', 'Despeje em forma untada, adicione gotas de chocolate e asse a 180 °C por 35 minutos.'], substituicoes: [] },
  { id: 112, nome: 'Bolo de Amêndoas com Coco', categoria: RecipeCategory.DOCES_E_MASSAS, carb: 0, porcoes: '4 porções', tags: ['Bolo', 'Amêndoas', '40 min'], image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-amendoas-com-coco-01-730x730.jpg', ingredientes: ['3 ovos', '1/2 xícara (chá) de xilitol (ou açúcar de coco)', '1 iogurte grego', '1 xícara (chá) de queijo curado', '2 xícaras (chá) de coco ralado', '1 xícara (chá) de amêndoas', '1 colher (sopa) de fermento em pó', 'Lascas de amêndoas e coco para finalizar'], modo_preparo: ['Bata no liquidificador ovos, xilitol, iogurte, queijo e coco até misturar bem.', 'Transfira para tigela, adicione amêndoas e fermento, mexendo até incorporar.', 'Despeje em forma untada, salpique lascas de amêndoas e coco.', 'Asse a 180 °C por 30 minutos.'], substituicoes: [] },
];

export const BONUSES: Bonus[] = [
  {
    title: '12 Receitas de Bolos Deliciosos e Seguros',
    image: 'https://www.receiteria.com.br/wp-content/uploads/bolo-de-flocao-zero-acucar.jpeg',
    content: 'Explore nossa coleção exclusiva de bolos feitos especialmente para quem precisa controlar o açúcar, mas não abre mão do sabor.',
    recipes: BONUS_CAKES_RECIPES,
  },
  {
    title: '10 Sobremesas Low Carb',
    image: 'https://i.postimg.cc/jdbjXyLg/DOCESLIBERADOS.png',
    content: 'https://drive.google.com/file/d/15kIFk5Vj2mzcKXqZrWfvLkTq1XQlHeK0/preview',
    isPdf: true,
  },
  {
    title: '50 Receitas de Pães Zero Glúten',
    image: 'https://i.postimg.cc/HkSsdK3R/P-ES.png',
    content: 'https://drive.google.com/file/d/1nSHa_lWhAcZAzk_9Ry_8QWTchAFXq0nn/preview',
    isPdf: true,
  },
  {
    title: '9 Chás para Controlar o Açúcar',
    image: 'https://i.postimg.cc/rwyw6cG5/CH-S.png',
    content: 'https://drive.google.com/file/d/1NmTzpiHg02UcfQ5AynIAmiwLhzWb-48B/preview',
    isPdf: true,
  },
  {
    title: 'Guia de Substituições Emergenciais',
    image: 'https://i.postimg.cc/FK7FRZBR/SUBSTITUI-ES.png',
    content: 'https://drive.google.com/file/d/158XL7idvnrg1t-hgz5-VxXVwQww0fBZE/preview',
    isPdf: true,
  },
];
